apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: >-
      [{"addresses":["172.31.62.250"],"port":30892,"protocol":"TCP","serviceName":"hw2:springboot-hw3","allNodes":true}]
  creationTimestamp: '2023-11-28T01:28:58Z'
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:field.cattle.io/publicEndpoints: {}
        f:spec:
          f:externalTrafficPolicy: {}
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":8080,"protocol":"TCP"}:
              .: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: agent
      operation: Update
      time: '2023-11-28T01:28:58Z'
  name: springboot-hw3
  namespace: argocd1
  resourceVersion: '1176744'
  uid: 1679fd42-8dc2-48a9-88e1-b58e33baea22
spec:
  clusterIP: 10.43.93.61
  clusterIPs:
    - 10.43.93.61
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 30892
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-hw2-survey
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
