apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["hw2/survey"]'
    management.cattle.io/ui-managed: 'true'
  creationTimestamp: '2023-10-07T16:55:08Z'
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:field.cattle.io/targetWorkloadIds: {}
            f:management.cattle.io/ui-managed: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"61e5b7df-4dea-41db-bca6-319099a20e52"}: {}
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":8080,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: agent
      operation: Update
      time: '2023-10-07T16:55:08Z'
  name: survey
  namespace: hw2
  ownerReferences:
    - apiVersion: apps/v1
      controller: true
      kind: Deployment
      name: survey
      uid: 61e5b7df-4dea-41db-bca6-319099a20e52
  resourceVersion: '16539'
  uid: 631d2a8f-2c63-4df8-8d6c-348152027d44
spec:
  clusterIP: 10.43.226.18
  clusterIPs:
    - 10.43.226.18
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: survey
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-hw2-survey
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
